### ISSUE TITLE
sortJSON does not preserve empty line after sort

### ISSUE THREAD

**Issue by zafarella** [gruntjs/grunt#1547]
defined as:
```yaml    
sortJSON:
      src: "<%= yeoman.app %>/i18n/*.json"
      options:
        spacing: 2
```

Sorts the json, however it truncates the last empty line in the file, which is uncomfortable  when using diffs in something like github especially in collaborative environment.
What you get those json files always getting in the change list even though you didn't modified them.

The sorting should not remove last empty line in files. Or add an option.
